version: "3.7"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test

  release:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    # This is set this way to make things easier in the Actions workflows.
    image: image

  run-model:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - ./test/config.json:/data/input/config.json:ro
      - ./test/adult_par.json:/data/input/adult_par.json:ro
      - ./test/aqua_par.json:/data/input/aqua_par.json:ro
      - ./output:/data/output:rw
      - ./schema:/data/schema:ro

