demo: # MicroMoB-BH-RM
  name: MicroMoB (Beverton-Holt Aquatic and Ross-Macdonald Adult Mosquitoes Only)
  origin: dd-harp (Disease Dynamics - Health Analytics for Robust Policy)
  enabled: true # Set to false if your repository is private
  imageURL: ghcr.io/dd-harp/MicroMoB-connector/MicroMoB-connector:latest
  metaURLs: # (Optional) URLs with more data about the model, to be displayed in the UI
    code: https://cran.r-project.org/web/packages/MicroMoB/index.html
    website: https://dd-harp.github.io/MicroMoB/
  description: |
    This is a simple aquatic and adult mosquito model that is defined
    on a set of points in space and most parameters are allowed to vary over 
    space and time.
  supportedSchemas:
    input: MicroMoBBHRMInputBatch
    output: MicroMoBBHRMOutputBatch